### PR TITLE
Finetune Paligemma for Object Detection

### PR DESCRIPTION
**Pull request by adityagandhamal**
Addresses the object detection task in #6 

@ariG23498, I have a few suggestions that I'd like to discuss before moving ahead

As far as finetuning is concerned, I am thinking of adding two methodologies to it:
1. LoRA
2. Prompt-Learning

along with implementing LR-scheduler and mixed-precision training with gradient scaling to address memory issues.

Additionally, since this was my first time hands-on with Hugging Face, I encountered a few errors while setting up the codebase which I'm assuming any first-timer would also come across. Given this, I'd like to implement the following changes to the code
- a `login()` step before pushing the dataset to hub in `create_od_dataset.py`
- error handling and logging in `object_detection_ft.py` for Gemma Access Request and other possible errors
- format existing code into a Class structure for better readability 

lmk your opinion

### CODE REVIEW

**Comment by ariG23498** [comment]
@adityagandhamal thanks for the great suggestions.

For this PR I would like for you to just refactor the scripts and notebooks to their individual folders, and update the README. Once that is done, I would like another PR for the ideas you have listed above.

How does that sound?

**Comment by ariG23498** [comment]
Any updates on this @adityagandhamal

**Comment by adityagandhamal** [comment]
Hi @ariG23498!
Sorry for not getting back to you sooner, I was a bit occupied last week. 

> For this PR I would like for you to just refactor the scripts and notebooks to their individual folders, and update the README. Once that is done, I would like another PR for the ideas you have listed above.

Yep, this sounds perfect.
I'll make the changes defined within the scope of this PR as you've mentioned and create a new PR for the suggestions.

**Comment by ariG23498** [comment]
No worries. Do let me know if you need any help from my end.

**Comment by adityagandhamal** [comment]
Hey @ariG23498, I've moved `create_od_dataset.py` and `object_detection_ft.py` scripts along with the `license_plate_detection_paligemma_ft.ipynb` notebook into a new folder `object_detection`. I have also added a `README.md` for the same.

**Review by ariG23498 — APPROVED** [review]
Thanks for the great contribution!

Looks good to me.

**Pull request merged**
